### ISSUE TITLE
[ feature ] improve panel dragging  

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#125]
Sometimes I can't drag a panel directly to the last position in the Controller.
I can only place it in the position above the last one.
And then I have to drag it again. 

If I wait a couple of seconds, sometimes it works, but it's not very responsive. 

![mo](https://github.com/user-attachments/assets/ffecf5c7-6409-4022-a610-144d8bed97f2)

---

If a Controller has 2 columns, it's even harder.  

![mo1](https://github.com/user-attachments/assets/75f2c0d9-cb90-42f1-a625-18be5037d862)

**Comment by JorgeR81** [comment]
The weird thing is that sometimes this works perfectly. 

When it starts working, it works well every time.

**Comment by chrisgoringe** [comment]
Made a number of changes on branch. You should now be able to drag to the bottom of each column, and it will be positioned there (unless it doesn't fit, in which case it goes at the top of the next.

**Comment by JorgeR81** [comment]
I didn't notice any differences.

The issue is still these. I can't drag a panel to the bottom position. 

- With a single column, sometimes it works, sometimes not.
But it's not completely random. When it works, it always works for a while. And when it fails, it always fails for a while. 

- Between 2 columns, it never works. 
First I need to move the panel to a position in the 2nd column. And then I can drag it to the last position. 

I use Google Chrome, by the way.

**Comment by chrisgoringe** [comment]
I believe the other fixes on 0.9.9 will resolve this. Please retest once that branch is stable.

**Comment by JorgeR81** [comment]
The issue is still there, with 0.9.9 stable.

I believe I always had this, since the beginning.

**Comment by chrisgoringe** [comment]
This must be related to #113

**Comment by chrisgoringe** [comment]
OK, I just pushed a small update which has some additional debugging code in around the area hinted at in this
![376562472-2a66cb02-cfd6-4788-ba6d-9e20ba18f288](https://github.com/user-attachments/assets/79108589-2a45-42a1-a9f8-fbd78a9578b9)

Incidentally, if you ever see an "Uncaught" error message in the console when something isn't working, it is always helpful to post it!

**Comment by JorgeR81** [comment]
> OK, I just pushed a small update which has some additional debugging code in around the area hinted at in this

Yes, I don't see this error anymore while dragging. 
But the original issue still persists. 

---

Also, I think the issues with 1 or 2 columns may have different causes.

Because with one column sometimes it works. 
But with 2 columns it never works.

**Comment by JorgeR81** [comment]
While making new workflows, I finally understand what's going on !

This issue is related to de `Load Image` node size and the Controler size. 

Basically, If a Controller requires 2 columns to fit all nodes, including a `Load Image` node, at its minimum image size, it will not have this issue. 
But If the reason a Controller has 2 columns is only the `Load Image` node size, it will have this issue.

I can explain better with images.

---

 This is the workflow with the issue ( only 1 columns show up ).

![flux issue](https://github.com/user-attachments/assets/67b42030-bf0f-4ef1-9425-54359918d440)

---

This is the same workflow with the issue, after refreshing the browser.
In the Controller, if I reduce the image size I can fit all nodes in a single column ( not pictured ).

![issue](https://github.com/user-attachments/assets/110ddfee-e089-4250-a364-4cacea719f9b)

---
This is a very similar workflow without the issue ( the 2nd column always shows up )

The only difference between them is that the Controller is shorter.
And this shorter Controller will have 2 columns, even If I realize the "load image" node, to its minimum size ( not pictured ).

![no_issue](https://github.com/user-attachments/assets/b93240f5-016c-42ec-b811-1c2f69682469)
