### ISSUE TITLE
[Bug] Controller window is expanding...

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#197]
@chrisgoringe Help 😅 

https://github.com/user-attachments/assets/05b8e734-18c1-4430-8f2c-64655d869d47

**Comment by chrisgoringe** [comment]
ok, I've backed the rescaling out until I work this out!

**Comment by LukeG89** [comment]
It's still expanding!

**Comment by chrisgoringe** [comment]
sorry - broke it again - try now

**Comment by LukeG89** [comment]
Fixed now!

**Comment by JorgeR81** [comment]
Yes It's fixed.

I still have as scaling issue in a specific workflow ( https://github.com/chrisgoringe/cg-controller/issues/195#issuecomment-2432189479 ) that's probably something workflow related ( it's al older workflow ).
