### ISSUE TITLE
[Bug] Black window when you open/create empty canvas (toggle on/off)

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#235]
Branch 1.1

When creating or opening a blank canvas, a black window is displayed, even though the toggle button is off:

![black_window_empty_canvas_toggle_off](https://github.com/user-attachments/assets/3eb0a0bf-cb5a-4b4a-a826-159806632a18)
 
The black window is shown even when you toggle on and refresh the page:

![black_window_empty_canvas_toggle_on](https://github.com/user-attachments/assets/33f11a2c-c8b8-421a-a8a4-cd3f84c22b35)

**Comment by chrisgoringe** [comment]
beleive this is now fixed on 1.2

**Comment by LukeG89** [comment]
Yes, it's fixed! However, there is still a problem with empty canvas in 1.2
