### ISSUE TITLE
[ feature ] option to hide file type in "loader" nodes 

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#467]
Can we have an user option to hide the file type in "loader" nodes ? 

Most of the files are `safetensors` anyways. 
 
This would make it easier to read the file names, especially when there are lots of files and long names ( like loras ). 

ComfyUI does not have this option, but it's a well known option, in the OS ( e.g. Windows )

**Comment by chrisgoringe** [comment]
Done in dev. Should apply to all combo boxes.

**Comment by JorgeR81** [comment]
It works.

But I still see them in the Power Lora Loader

Can they be hidden there, too ?

**Comment by chrisgoringe** [comment]
done on 1.7

**Comment by JorgeR81** [comment]
It works.
